name: lark_auth_server
server_id: 1
log: "./configs/logger.yaml"
grpc_server:
  name: lark_auth_server
  server_id: 1
  port: 6600
  max_connection_idle: 0
  max_connection_age: 0
  max_connection_age_grace: 0
  time: 7200000
  timeout: 20000
  connection_limit: 2000
  streams_limit: 2000
  max_recv_msg_size: 4096
  credential:
    cert_file: ./configs/tls/grpc/server.pem
    key_file: ./configs/tls/grpc/server.key
    enabled: true
  jaeger:
    host_port: "localhost:6831"
    sampler_type: "const"
    param: 1
    log_spans: true
    buffer_flush_interval: 1
    max_packet_size: 0
    enabled: false
etcd:
  endpoints: ["localhost:2379"]
  username:
  password:
  schema: lark
  read_timeout: 5000
  write_timeout: 5000
  dial_timeout: 5000
mysql:
  max_open_conns: 20
  max_idle_conns: 10
  max_lifetime: 120000
  max_idle_time: 7200000
  charset: utf8
  sources:
    - {address: "localhost:3306",username: root,password: 139639hh,db: lark_user}
  replicas:
redis:
  address: ["localhost:6379"]
  db: 0
  password: lark2022
  prefix: "LK:"
chat_member_server:
  name: lark_chat_member_server
  cert:
    cert_file: ./configs/tls/grpc/server.pem
    enabled: true
    server_name_override: lark.com
jaeger:
  host_port: "localhost:6831"
  sampler_type: "const"
  param: 1
  log_spans: true
  buffer_flush_interval: 1
  max_packet_size: 0
  enabled: false
github_oauth2:
  client_id: "91207c9fb0fb556c0753"
  client_secret: "61618bf55fa6127e8d2701a62a308fdfea99c844"
  redirect_url: "http://localhost:8088/open/auth/oauth2/github/callback"

