endpoint: 'localhost:9000'
options:
  secure: false
  credentials:
    access_key: 'root'
    secret_key: '139639hh'
    token: ''
bucket:
  bucket_names: ["documents","photos","videos"]
  make_bucket_options:
    region: 'cn-gz'
    objectLocking: false
  put_object_options:
    encrypted: false